version: 2
dist: bin
builds:
  - binary: ssl_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - mips64le
    flags:
      - -v
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.Commit}}
      -X github.com/prometheus/common/version.Branch={{.Env.APP_BRANCH}}
      -X github.com/prometheus/common/version.BuildUser={{.Env.APP_USER}}@{{.Env.APP_HOST}}
      -X github.com/prometheus/common/version.BuildDate={{.Date}}
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '(?i)\[skip changelog\]'
      - '^Merge '
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Tests
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Maintenance
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: Others
      order: 999

release:
  github:
    owner: piotrkochan
    name: ssl_exporter
  prerelease: auto
dockers:
  - image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}"
    image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-amd64"
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-arm64"
  - name_template: "{{.Env.APP_DOCKER_IMAGE_NAME}}:latest"
    skip_push: "auto"
    image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-amd64"
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-arm64"
