[[IgnoredVulns]]
id = "GO-2026-5932"
reason = "The project imports golang.org/x/crypto/ocsp only and does not import or call any affected golang.org/x/crypto/openpgp package. Verified with govulncheck."
