{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ssl-exporter.fullname" . }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ssl-exporter.fullname" . }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ssl-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ssl-exporter.fullname" . }}
{{- end }}
