{{- if and .Values.webConfig.enabled (not .Values.webConfig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssl-exporter.webConfigSecretName" . }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  web-config.yaml: |
    {{- $cfg := dict }}
    {{- if .Values.tls.enabled }}
    {{- $tlsCfg := dict "cert_file" (printf "%s/tls.crt" .Values.tls.mountPath) "key_file" (printf "%s/tls.key" .Values.tls.mountPath) }}
    {{- $_ := set $cfg "tls_server_config" $tlsCfg }}
    {{- end }}
    {{- range $k, $v := .Values.webConfig.data }}
    {{- $_ := set $cfg $k $v }}
    {{- end }}
    {{- toYaml $cfg | nindent 4 }}
{{- end }}
